### ISSUE TITLE
Ability to pull in .js files

### ISSUE THREAD

**Issue by devPalacio** [trellistk/simple-sls-ssr#14]
**Is your feature request related to a problem? Please describe.**

We currently don't have a way to develop JavaScript outside of the html file.

**Describe the solution you'd like**
Enable developers to develop JavaScript in a .js file outside of the html file.

**Comment by ambergkim** [comment]
Acceptance Criteria:
- [ ] JavaScript should load before the end of the `</body>` tag
- [ ] It should pull from a folder to store javascript files
